### ISSUE TITLE
How do you application materials?

### ISSUE THREAD

**Issue by lingme** [Crauzer/lol2gltf#1]
I see how you use the Microsoft 3D viewer, how posted skin material ?

**Comment by Crauzer** [comment]
https://github.com/LoL-Fantome/Fantome.Libraries.League/commit/8894ef21d0058ee5ddf13e11c119af198602d8ca

**Comment by lingme** [comment]
I feel your  support speed is amazing

**Comment by lingme** [comment]
I try to  add unit test for this project, because i feel this project need test more models
