### ISSUE TITLE
Lol2GltfGUI unable to load/convert certain Rengar animations.

### ISSUE THREAD

**Issue by Logzombie** [Crauzer/lol2gltf#10]
Upon attempting to load the specific animations "Rengar_attack4.anm, Rengar_spell2.anm, Rengar_channel.anm", the GUI version of Lol2Gltf appears to crash. Closing almost instantly after one of these files are loaded alongside the skl and skn files in the application.
Oddly enough, I have managed to convert the entirety of Aurelion Sol's mesh and animations with very little issue. So this came as a surprise.

I then attempted to use the non-GUI version of Lol2gltf in an attempt to circumvent this issue. However, still able to convert the other files, the non-GUI version appeared to throw out this error message and producing no results. (See attached)
![cmd_pik8L7JlGA](https://user-images.githubusercontent.com/50374409/103670961-304ab300-4f72-11eb-9f38-1d9215ed43f1.png)

I am somewhat unsure if I have made a mistake somewhere or if these particular animations appear to be janky with the current version of the program, albiet this appears to occur on previous versions as well. I am also unsure if this is specific to Rengar or can occur on other potential models. Please let me know if there is a potential workaround or if this will be in the works for being fixed.

**Comment by scmanjarrez** [comment]
Any update?

**Comment by WollieWoltaz** [comment]
I don't know why this happens, but I did manage to get a .glb file with the 3 specific animations that were mentioned in the OP.
https://mega.nz/folder/KAkAhDJL#9MHw8S0uDAMB54Uqwgm3zQ

**Comment by scmanjarrez** [comment]
Fixed in https://github.com/LoL-Fantome/LeagueToolkit/pull/108

**Comment by Crauzer** [comment]
https://github.com/Crauzer/lol2gltf/releases/tag/3.0.0-beta.4
