### ISSUE TITLE
the ui window prevents me from pressing the "convert" button.

### ISSUE THREAD

**Issue by jupi-ter** [Crauzer/lol2gltf#14]
perhaps a problem with resolutions? i have a 16:9 monitor but i couldn't get it to work normally
![image](https://user-images.githubusercontent.com/102880647/198851270-cd27698c-0806-4de6-bef1-e466cc88a414.png)

had to set my monitor orientation to portrait to be able to see it, lol.
![image](https://user-images.githubusercontent.com/102880647/198851311-1f923282-b74d-4bef-9273-fd2bd04123a9.png)

**Comment by HalanoSiblee** [comment]
Yes same

**Comment by Crauzer** [comment]
Fixed in [3.0.0-beta.1](https://github.com/Crauzer/lol2gltf/releases/tag/3.0.0-beta.1)
