### ISSUE TITLE
can i convert mapgeo to gltf?

### ISSUE THREAD

**Issue by Lohaa** [Crauzer/lol2gltf#15]

**Comment by Neinndall** [comment]
as he said in the discord, in the final version

**Comment by Crauzer** [comment]
The code for it already exists, I just need to make UI for it
![image](https://user-images.githubusercontent.com/18646077/212323981-d634faec-315d-4157-8f67-fdae4911eafd.png)

**Comment by Crauzer** [comment]
Closing in favor of: https://github.com/Crauzer/lol2gltf/issues/19
