### ISSUE TITLE
Skn & skl without animations

### ISSUE THREAD

**Issue by HalanoSiblee** [Crauzer/lol2gltf#16]
i'm using lol2gltf cli but it's forcing me to add animations folder while i just need a rigged body like Obsidian do
$ **lol2gltf skn2gltf-rigged -s skin.skl -m skin.skn -o skin.glb**
no need to add --animations

**Comment by Crauzer** [comment]
Should work in https://github.com/Crauzer/lol2gltf/releases/tag/3.0.0-beta.4
