### ISSUE TITLE
Complicated model should be how to convert?

### ISSUE THREAD

**Issue by lingme** [Crauzer/lol2gltf#2]
Hi, I came to ask questions, such as the epic skin how to convert?Because there are a lot of texture and mesh？

**Comment by Crauzer** [comment]
It should be as easy as any other model.

I'll make guides on how to use the tool soon.

**Comment by Crauzer** [comment]
https://github.com/Crauzer/lol2gltf/wiki

**Comment by lingme** [comment]
But the situation is not very optimistic, think some epic of the skin, there will be a lot of texture and components, the most let me feel doubt is, for example, the DJ's Sona

**Comment by Crauzer** [comment]
With the cmd tool it's just tedious to write out the material and texture names.

I'm working on an application that has actual UI right now.

**Comment by lingme** [comment]
Thank you for your answer, but what really makes me puzzled is that, if find the dependence of Sub mesh and DDS file?Because there are

**Comment by Crauzer** [comment]
I'm not sure what exactly you mean, but this should help you:
https://github.com/Crauzer/lol2gltf/wiki/Dumping-info-about-a-Simple-Skin-(SKN)

**Comment by lingme** [comment]
Yes，Is this, I found the all mesh name, but don't know how to map, because the name of the mesh and DDS file name is not the same, Simple model is very good, but complex, such as Yone, meshs name and DDS is also very much, the human eye judgment will lead to wrong sometimes

**Comment by Crauzer** [comment]
This isn't much of an issue though, since you will open the glTF in a modeling program anyways. You can play around with textures there and bundle it better.

The only way to resolve textures for materials is to parse BIN files which I honestly don't plan on doing since it will create even more complexity and confusion.

**Comment by lingme** [comment]
ok, thanks, I the GLTF everywhere, why in the Blender, not selected components,Everything is as a whole, I am not very familiar with the model

**Comment by Crauzer** [comment]
I'm not sure what you mean 😄.

glTF can be opened in a lot of 3D software except ones from Autodesk.

**Comment by lingme** [comment]
Sorry, it is a little confusion, I am not very familiar with 3d software, thank you for your patience reply, I hope to participate in the development of this conversion tool GUI work, when the time comes I will submit a pull request
