### ISSUE TITLE
Broken animations

### ISSUE THREAD

**Issue by APPenchev** [Crauzer/lol2gltf#27]
I successfully exported the Renekton skin, but now there are issues with some of the animations when I imported them into blender. Someting i've noticed is that they are the same animations that also used to crash version 2.0.0 when being loaded in the UI verison #11  before it was fixed in 3.0.0 beta 4.

the "attack_1" animation works completely fine.
![renecbug3](https://user-images.githubusercontent.com/36088861/217105411-7ceda3e5-9a73-42c5-80e1-41bbc311716d.gif)

the "idle_1" animation looks... interesting
![renecbug4](https://user-images.githubusercontent.com/36088861/217105542-20393ece-4730-48dd-b097-bdfc7d4ca4c0.gif)

**Comment by Crauzer** [comment]
I'm pretty sure I know what causes the issue but it is not related to the renekton animation files.
I think you'll encounter this with compressed animations which are used for exporting more than once. So if you export 2+ gltf files with the same loaded animation instance, it'll be bugged.
It should work correctly when you export only once.

https://user-images.githubusercontent.com/18646077/217109912-9e6754cb-730e-4915-b490-e3ca884bdf80.mp4

**Comment by APPenchev** [comment]
Yes, that fixed the issue. Thanks, once again.

**Comment by Crauzer** [comment]
https://github.com/LeagueToolkit/LeagueToolkit/issues/239
