### ISSUE TITLE
Kog Maw Skin 37

### ISSUE THREAD

**Issue by Ruinedgod** [Crauzer/lol2gltf#30]
Error: System.NotSupportedException: Reading legacy animations is not supported at CommunityToolkit.Diagnostics.ThrowHelper.ThrowNotSupportedException(String message) at LeagueToolkit.Core.Animation.UncompressedAnimationAsset.ReadLegacy(BinaryReader br) at LeagueToolkit.Core.Animation.UncompressedAnimationAsset..ctor(Stream stream) at LeagueToolkit.Core.Animation.AnimationAsset.Load(Stream stream) at lol2gltf.Pages.SkinnedMesh.AddAnimations(IEnumerable`1 animationFiles) in D:\a\lol2gltf\lol2gltf\lol2gltf\Pages\SkinnedMesh.razor:line 275 at lol2gltf.Pages.SkinnedMesh.AddAnimations() in D:\a\lol2gltf\lol2gltf\lol2gltf\Pages\SkinnedMesh.razor:line 261

**Comment by Crauzer** [comment]
Should be fixed now
