### ISSUE TITLE
Lots of Legacy Animation Errors

### ISSUE THREAD

**Issue by Sir-DJ-Cat** [Crauzer/lol2gltf#31]
On a bunch of different heroes (e.g. Amumu, Rammus, and some others) I get this error when trying to import the animations:

> Error: System.NotSupportedException: Reading legacy animations is not supported at CommunityToolkit.Diagnostics.ThrowHelper.ThrowNotSupportedException(String message) at LeagueToolkit.Core.Animation.UncompressedAnimationAsset.ReadLegacy(BinaryReader br) at LeagueToolkit.Core.Animation.UncompressedAnimationAsset..ctor(Stream stream) at LeagueToolkit.Core.Animation.AnimationAsset.Load(Stream stream) at lol2gltf.Pages.SkinnedMesh.AddAnimations(IEnumerable`1 animationFiles) in D:\a\lol2gltf\lol2gltf\lol2gltf\Pages\SkinnedMesh.razor:line 275 at lol2gltf.Pages.SkinnedMesh.AddAnimations() in D:\a\lol2gltf\lol2gltf\lol2gltf\Pages\SkinnedMesh.razor:line 261

**Comment by Crauzer** [comment]
This should be fixed now
