### ISSUE TITLE
Cant open the lol2gltf.CLI file

### ISSUE THREAD

**Issue by SLINX84** [Crauzer/lol2gltf#37]
It just dont open i tried anything

**Comment by fenobronas** [comment]
you aren't supposed to open it per se

to use it, you gotta go to the folder where it is, and open cmd, like this

![imagem_2023-10-11_092655847](https://github.com/Crauzer/lol2gltf/assets/90477658/bb1ee533-a8d7-4471-8415-392e7dfbd971)

after that you can use it as per the wiki.

lol2gltf.CLI.exe (insert what you wanna do)
