### ISSUE TITLE
Import Unreal Egine 4 failed.

### ISSUE THREAD

**Issue by lingme** [Crauzer/lol2gltf#4]
Hello, I need your help, I tried import gltf model to Unreal Engine 4（version 4.25.3），but import failed, I use the plugin is https://c4gio.itch.io/gltf-for-ue4?download (version gltf-for-ue4-ue4.25-stable)
![Capture](https://user-images.githubusercontent.com/32844254/93103116-d1b9aa80-f6de-11ea-875a-681086015684.PNG)

**Comment by Crauzer** [comment]
This is an issue with the UE4 importer plugin, I suggest you submit a bug report to them.

**Comment by Crauzer** [comment]
I believe the Windows 10 3D Model Viewer also suffers from this same issue.

**Comment by lingme** [comment]
Thank you for your answer patiently, but Windows 10 3DModel Viewer is working, I tried to import another from Sketchfab download the 3d model, UE4 is working, but use lol2gltf library be not allowed

**Comment by TheKillerey** [comment]
![image](https://user-images.githubusercontent.com/18242778/93212283-af697080-f762-11ea-8368-6569b41b01f3.png)
Riot has multiple Roots for the Character. Unreal Engine support only 1 Root. What you need to do is to go into Blender and create a new root. Drag all of the other ones into it. So you get only 1 Main Root

**Comment by lingme** [comment]
Nice, thanks you, I will try .

**Comment by lingme** [comment]
I trying create one Root, it is working , thanks
