### ISSUE TITLE
Neeko Winter Wonderland skin not converting properly

### ISSUE THREAD

**Issue by ileonardo-c** [Crauzer/lol2gltf#6]
I convert Neeko's Winter Wonderland skin and the model comes out with some flaws, with or without the skeleton.
Preview img: [Neeko_Winter_Wonderland-lol2gltf-2020-10-10
](https://prnt.sc/uwsu51)

**Comment by Crauzer** [comment]
Can you please elaborate on the issue ?
I do not see any flaws with the model in your screenshot so I'm not sure what you're referring to.

**Comment by ileonardo-c** [comment]
I used teemo.gg as a base for you to see the difference:
[lol2gltf](https://prntscr.com/uwucia)
[teemo_gg](https://prntscr.com/uwuclq)

**Comment by TheKillerey** [comment]
I will also look into it.

**Comment by TheKillerey** [comment]
![image](https://user-images.githubusercontent.com/18242778/95664628-f2dcb200-0b49-11eb-804b-2c6b49126d65.png)
Thats not a convertion problem. The material for it needs be hide. 2 meshes are overlapping.

**Comment by ileonardo-c** [comment]
during conversion is it possible to choose the materials to be hidden?

**Comment by TheKillerey** [comment]
In mostly all. Otherwise you need to delete the materials

**Comment by ileonardo-c** [comment]
I don't know if you are getting away from it, but there is a tutorial? Because I saw that you changed the `.bin` (League Binary) to `.py` and I wouldn't know how to join it again in `.gltf`

**Comment by TheKillerey** [comment]
What do you want? I don't what your trying.

**Comment by ileonardo-c** [comment]
what tools used to correct the model and apply it again in lol2gltf with an animation

**Comment by TheKillerey** [comment]
Use blender for that. My tool is not free

**Comment by Crauzer** [comment]
As @TheKillerey explained above, the issue you have is that there are overlapping meshes.

Use a better/different model viewer such as Blender or Babylon.JS.
