### ISSUE TITLE
SKL and ANM conversion without SKN?

### ISSUE THREAD

**Issue by Mawrak** [Crauzer/lol2gltf#9]
Good day. 
I have SKL and ANM files, they are from a different game (Telltale games), but they might be similar to the files used by lol2, as they use both SKL for skeleton and ANM for animation. 

The game does not use SKN files though. 

Here are some example files: https://drive.google.com/file/d/1dcJN3m26HvVDyZIrbmR0RaQZRe4gWIDJ/view?usp=sharing

Of course, if these are not similar to the lol2 format, there is no point in even trying to do anything with them, but if they are, is it possible to attempt to do the conversion without the mesh (SKN) file?

**Comment by Crauzer** [comment]
This program only supports League of Legends assets and such a mesh is required.
